name: Sort JSON on Pull Requests

on:
  pull_request:
    paths:
      - "**/*.json" # Trigger only for locale json changes
      # - "client/packages/common/src/intl/locales/**/*.json" # Trigger only for locale json changes

jobs:
  sort-json:
    runs-on: ubuntu-latest

    steps:
      - name: Setup cache for jq
        uses: actions/cache@v3
        with:
          path: /usr/bin/jq
          key: jq-cache

      - name: Install jq if not cached
        run: |
          if ! command -v jq &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y jq
          else
            echo "jq is already installed, skipping installation."
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sort translation files
        run: |
          TRANSLATION_FILES=($(find ./files/ -type f -name "*.json"))
          for file in "${TRANSLATION_FILES[@]}"; do
            echo "Sorting $file..."
            jq --sort-keys . "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
          done

      - name: Commit and push changes
        run: |
          # Check for changes
            echo "checking for changes"
          if [ "$(git status --porcelain)" ]; then
            echo "changes found"
          else
            echo 'No changes to commit.'
