name: Sort JSON on Pull Requests

on:
  pull_request:
    paths:
      - "client/packages/common/src/intl/locales/**/*.json" # Trigger only for locale json changes

jobs:
  sort-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up jq (JSON processor)
      - name: Set up jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Step 3: Sort JSON files
      - name: Sort JSON files
        run: |
          # Find all changed JSON files in the PR
          for file in $(git diff --name-only --diff-filter=d origin/main | grep '\.json$'); do
            echo "Sorting $file..."
            jq --sort-keys . "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
          done

      # Step 4: Commit and push changes if necessary
      - name: Commit and push changes
        run: |
          # Check for changes
          if [ "$(git status --porcelain)" ]; then
            echo "Changes detected, committing..."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: sorted JSON files"
            git push
          else
            echo "No changes to commit."
